export const MOTIVATION_TIPS: string[] = [
  "One step at a time – your future self will thank you.",
  "Feel the power of progress – believe in your pace.",
  "Discipline is key – every step is a small victory.",
  "One step at a time – strong habits shape strong lives.",
  "Discipline is key – the journey is worth it.",
  "Step forward with courage – your future self will thank you.",
  "Push your limits – small actions lead to big changes.",
  "Health is wealth – the journey is worth it.",
  "Wellness begins with effort – believe in your pace.",
  "Energy is built daily – every step is a small victory.",
  "Feel the power of progress – the journey is worth it.",
  "Every step counts – believe in your pace.",
  "Step forward with courage – you're building resilience.",
  "One step at a time – believe in your pace.",
  "Health is wealth – choose consistency over intensity.",
  "Every step counts – choose consistency over intensity.",
  "Momentum matters – today’s effort fuels tomorrow.",
  "One step at a time – small actions lead to big changes.",
  "Walk your way to wellness – choose consistency over intensity.",
  "Momentum matters – greatness is built step by step.",
  "Health is wealth – strong habits shape strong lives.",
  "Wellness begins with effort – small actions lead to big changes.",
  "Feel the power of progress – today’s effort fuels tomorrow.",
  "Push your limits – believe in your pace.",
  "You're doing great – every step is a small victory.",
  "One step at a time – every step is a small victory.",
  "Every step counts – greatness is built step by step.",
  "Keep moving – strong habits shape strong lives.",
  "Step forward with courage – believe in your pace.",
  "Momentum matters – every step is a small victory.",
  "Move with purpose – every step is a small victory.",
  "Keep moving – every step is a small victory.",
  "Discipline is key – choose consistency over intensity.",
  "Walk your way to wellness – every step is a small victory.",
  "Keep moving – small actions lead to big changes.",
  "Stay strong – believe in your pace.",
  "Wellness begins with effort – you're building resilience.",
  "Stay strong – the journey is worth it.",
  "Wellness begins with effort – the journey is worth it.",
  "Walk your way to wellness – you're building resilience.",
  "Keep moving – greatness is built step by step.",
  "One step at a time – today’s effort fuels tomorrow.",
  "Push your limits – you're building resilience.",
  "Stay strong – greatness is built step by step.",
  "Momentum matters – believe in your pace.",
  "Momentum matters – choose consistency over intensity.",
  "Every step counts – small actions lead to big changes.",
  "Momentum matters – small actions lead to big changes.",
  "Wellness begins with effort – your future self will thank you.",
  "Feel the power of progress – choose consistency over intensity.",
  "Discipline is key – believe in your pace.",
  "Step forward with courage – the journey is worth it.",
  "Walk your way to wellness – your future self will thank you.",
  "Discipline is key – you're building resilience.",
  "You're doing great – choose consistency over intensity.",
  "Keep moving – your future self will thank you.",
  "You're doing great – believe in your pace.",
  "Every step counts – today’s effort fuels tomorrow.",
  "Wellness begins with effort – every step is a small victory.",
  "You're doing great – you're building resilience.",
  "Push your limits – greatness is built step by step.",
  "Step forward with courage – choose consistency over intensity.",
  "Every step counts – strong habits shape strong lives.",
  "Feel the power of progress – your future self will thank you.",
  "Discipline is key – strong habits shape strong lives.",
  "Wellness begins with effort – greatness is built step by step.",
  "Step forward with courage – every step is a small victory.",
  "Discipline is key – your future self will thank you.",
  "Health is wealth – your future self will thank you.",
  "Momentum matters – strong habits shape strong lives.",
  "Move with purpose – choose consistency over intensity.",
  "Every step counts – you're building resilience.",
  "Push your limits – every step is a small victory.",
  "Feel the power of progress – greatness is built step by step.",
  "Discipline is key – today’s effort fuels tomorrow.",
  "Energy is built daily – small actions lead to big changes.",
  "Push your limits – choose consistency over intensity.",
  "Move with purpose – the journey is worth it.",
  "Health is wealth – every step is a small victory.",
  "Wellness begins with effort – strong habits shape strong lives.",
  "You're doing great – your future self will thank you.",
  "Health is wealth – you're building resilience.",
  "Walk your way to wellness – the journey is worth it.",
  "Wellness begins with effort – choose consistency over intensity.",
  "Move with purpose – you're building resilience.",
  "Momentum matters – your future self will thank you.",
  "Feel the power of progress – strong habits shape strong lives.",
  "Wellness begins with effort – today’s effort fuels tomorrow.",
  "Energy is built daily – believe in your pace.",
  "Stay strong – choose consistency over intensity.",
  "Energy is built daily – greatness is built step by step.",
  "Energy is built daily – your future self will thank you.",
  "Health is wealth – small actions lead to big changes.",
  "Walk your way to wellness – believe in your pace.",
  "You're doing great – strong habits shape strong lives.",
  "Energy is built daily – choose consistency over intensity.",
  "Step forward with courage – strong habits shape strong lives.",
  "Momentum matters – the journey is worth it.",
  "Stay strong – today’s effort fuels tomorrow.",
  "Discipline is key – small actions lead to big changes.",
  "Walk your way to wellness – strong habits shape strong lives.",
  "Move with purpose – today’s effort fuels tomorrow.",
  "Keep moving – you're building resilience.",
  "You're doing great – today’s effort fuels tomorrow.",
  "Every step counts – your future self will thank you.",
  "One step at a time – choose consistency over intensity.",
  "Every step counts – every step is a small victory.",
  "Energy is built daily – the journey is worth it.",
  "Keep moving – the journey is worth it.",
  "Move with purpose – greatness is built step by step.",
  "Step forward with courage – greatness is built step by step.",
  "Keep moving – today’s effort fuels tomorrow.",
  "Health is wealth – today’s effort fuels tomorrow.",
  "Keep moving – believe in your pace.",
  "Move with purpose – believe in your pace.",
  "Every step counts – the journey is worth it.",
  "Energy is built daily – today’s effort fuels tomorrow.",
  "Walk your way to wellness – small actions lead to big changes.",
  "Push your limits – your future self will thank you.",
  "You're doing great – greatness is built step by step.",
  "Health is wealth – believe in your pace.",
  "One step at a time – greatness is built step by step.",
  "Stay strong – small actions lead to big changes.",
  "Stay strong – you're building resilience.",
  "Momentum matters – you're building resilience.",
  "Move with purpose – your future self will thank you.",
  "Energy is built daily – you're building resilience.",
  "You're doing great – small actions lead to big changes.",
  "You're doing great – the journey is worth it.",
  "Discipline is key – greatness is built step by step.",
  "Push your limits – today’s effort fuels tomorrow.",
  "Stay strong – your future self will thank you.",
  "Push your limits – the journey is worth it.",
  "Move with purpose – small actions lead to big changes.",
  "Move with purpose – strong habits shape strong lives.",
  "Step forward with courage – today’s effort fuels tomorrow.",
  "Push your limits – strong habits shape strong lives.",
  "Feel the power of progress – small actions lead to big changes.",
  "Energy is built daily – strong habits shape strong lives.",
  "Step forward with courage – small actions lead to big changes.",
  "Keep moving – choose consistency over intensity.",
  "Walk your way to wellness – today’s effort fuels tomorrow.",
  "Feel the power of progress – you're building resilience.",
  "Stay strong – every step is a small victory.",
  "Walk your way to wellness – greatness is built step by step.",
  "Feel the power of progress – every step is a small victory.",
  "Health is wealth – greatness is built step by step.",
  "One step at a time – the journey is worth it.",
  "One step at a time – you're building resilience.",
  "Stay strong – strong habits shape strong lives.",
];
